"""SQLAlchemy ORM models for the Gia relational store.

All primary keys are server-side UUID v4 values.  Foreign keys carry the same
``Uuid`` type so that joins are always comparing like for like.  The ``Uuid``
type is native on Postgres and falls back to VARCHAR on SQLite (used in tests).
"""

import uuid
from datetime import datetime

from sqlalchemy import JSON, DateTime, Float, ForeignKey, String, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.base import Base


class User(Base):
    """One row per registered Gia user.

    Attributes:
        id:               UUID primary key — generated by the application.
        email:            Optional e-mail address; must be unique across all rows.
        created_at:       Row insertion timestamp, set by the database.
        profile:          Lazy one-to-one to ``Profile``.
        listening_events: Lazy one-to-many to ``ListeningEvent``.
        sessions:         Lazy one-to-many to ``ConversationSession``.
    """

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    email: Mapped[str | None] = mapped_column(String, unique=True, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    profile: Mapped["Profile | None"] = relationship("Profile", back_populates="user", uselist=False)
    listening_events: Mapped[list["ListeningEvent"]] = relationship(
        "ListeningEvent", back_populates="user"
    )
    sessions: Mapped[list["ConversationSession"]] = relationship(
        "ConversationSession", back_populates="user"
    )


class Profile(Base):
    """Extended per-user settings and Spotify OAuth tokens.

    Attributes:
        id:                       UUID primary key.
        user_id:                  FK → ``users.id`` (one-to-one).
        spotify_user_id:          Spotify's own user identifier (e.g. ``kolade_faj``).
        timezone:                 IANA timezone string, default ``"UTC"``.
        preferred_genres:         JSON array of genre strings.
        preferred_volume:         Normalised playback volume (0.0 – 1.0).
        spotify_access_token:     Short-lived access token; refreshed automatically.
        spotify_refresh_token:    Long-lived refresh token; persisted after each OAuth flow.
        spotify_token_expires_at: UTC expiry of the current access token.
        updated_at:               Last-modified timestamp, maintained by the database.
    """

    __tablename__ = "profiles"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("users.id"), unique=True)
    spotify_user_id: Mapped[str | None] = mapped_column(String, nullable=True)
    timezone: Mapped[str] = mapped_column(String, default="UTC")
    preferred_genres: Mapped[list[str]] = mapped_column(JSON, default=list)
    preferred_volume: Mapped[float] = mapped_column(Float, default=0.7)
    spotify_access_token: Mapped[str | None] = mapped_column(String, nullable=True)
    spotify_refresh_token: Mapped[str | None] = mapped_column(String, nullable=True)
    spotify_token_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    user: Mapped[User] = relationship("User", back_populates="profile")


class ListeningEvent(Base):
    """One row per track played — the raw signal for mood inference.

    Audio feature columns (energy, valence, tempo, danceability, key, mode) are
    nullable because they are enriched asynchronously by the Celery worker after
    the event is first recorded.

    Attributes:
        id:           UUID primary key.
        user_id:      FK → ``users.id``.
        track_uri:    Spotify track URI (e.g. ``spotify:track:4cOdK2wGLETKBW3PvgPWqT``).
        track_name:   Human-readable track title.
        artist_name:  Primary artist name.
        energy:       Spotify audio feature: energy (0.0 – 1.0).
        valence:      Spotify audio feature: musical positivity (0.0 – 1.0).
        tempo:        Estimated BPM.
        danceability: Spotify audio feature (0.0 – 1.0).
        key:          Musical key (0 = C, 1 = C♯/D♭, …, 11 = B).
        mode:         Modality: 1 = major, 0 = minor.
        played_at:    Timestamp when the track was played (from Spotify).
    """

    __tablename__ = "listening_events"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("users.id"))
    track_uri: Mapped[str] = mapped_column(String)
    track_name: Mapped[str | None] = mapped_column(String, nullable=True)
    artist_name: Mapped[str | None] = mapped_column(String, nullable=True)
    energy: Mapped[float | None] = mapped_column(Float, nullable=True)
    valence: Mapped[float | None] = mapped_column(Float, nullable=True)
    tempo: Mapped[float | None] = mapped_column(Float, nullable=True)
    danceability: Mapped[float | None] = mapped_column(Float, nullable=True)
    key: Mapped[int | None] = mapped_column(nullable=True)
    mode: Mapped[int | None] = mapped_column(nullable=True)
    played_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    user: Mapped[User] = relationship("User", back_populates="listening_events")


class ConversationSession(Base):
    """One row per voice conversation between a user and Gia.

    Attributes:
        id:         UUID primary key.
        user_id:    FK → ``users.id``.
        started_at: Timestamp when Gia greeted the user.
        ended_at:   Timestamp when the session ended; ``None`` while active.
        summary:    Free-text summary extracted after the session ends.
        intent_log: JSON array of intent/action dicts recorded during the session.
    """

    __tablename__ = "conversation_sessions"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("users.id"))
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    summary: Mapped[str | None] = mapped_column(String, nullable=True)
    intent_log: Mapped[list[dict]] = mapped_column(JSON, default=list)

    user: Mapped[User] = relationship("User", back_populates="sessions")
