"""Pydantic schemas for the /chat endpoint."""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class IntentType(str, Enum):
    """Possible intents the Router agent can classify."""

    MUSIC_FIND = "MUSIC_FIND"
    MUSIC_QUEUE = "MUSIC_QUEUE"
    ARTIST_INFO = "ARTIST_INFO"
    MOOD_CHECK = "MOOD_CHECK"
    MIXED = "MIXED"


class ExecutionPlan(BaseModel):
    """A plan for a single conversation turn, produced by the planner.

    The planner is the evolution of a flat intent classifier: instead of one
    label, it emits an ordered list of agents to run plus the extra real-world
    *signals* worth gathering first (e.g. weather).  This is what turns a set of
    isolated tools into a companion that reasons across them.

    Attributes:
        intent:     The primary classified intent (kept for telemetry / the
                    ``done`` event and backward compatibility).
        steps:      Ordered agent names to execute (``"dj"``, ``"artist"``,
                    ``"mood"``).
        signals:    Extra context signals to gather before/while running steps
                    (currently ``"weather"``).
        confidence: Planner confidence in the chosen intent (1.0 heuristic,
                    0.8 LLM, 0.5 fallback).
    """

    intent: IntentType
    steps: list[str] = Field(default_factory=list)
    signals: list[str] = Field(default_factory=list)
    confidence: float = 1.0


class ChatRequest(BaseModel):
    """Request body for ``POST /chat``.

    Attributes:
        message:    The user's natural-language input.
        user_id:    Optional UUID — enables personalised memory retrieval.
        session_id: Optional session identifier for multi-turn continuity.
                    Generated by the client and passed with every turn.
    """

    message: str = Field(min_length=1, max_length=2000)
    user_id: str | None = None
    session_id: str | None = None


class AgentTrace(BaseModel):
    """Timing and I/O record for a single agent invocation.

    Attributes:
        agent:      Agent name (e.g. ``"router"``, ``"dj"``).
        input:      Summary of what was passed in.
        output:     Summary of what was returned.
        latency_ms: Wall-clock time from invocation to return.
    """

    agent: str
    input: str
    output: str
    latency_ms: float


class ChatResponse(BaseModel):
    """Response from ``POST /chat`` (synchronous, non-SSE mode).

    Attributes:
        reply:             Gia's natural-language response.
        intent:            What the Router classified the request as.
        proactive:         Optional unprompted observation Gia surfaces.
        agent_traces:      Per-agent timing records for observability.
        user_context_used: Whether personalised user context was injected.
    """

    reply: str
    intent: IntentType
    proactive: str | None = None
    agent_traces: list[AgentTrace] = Field(default_factory=list)
    user_context_used: bool = False


class SSEEvent(BaseModel):
    """Shape of a single Server-Sent Event payload.

    Attributes:
        event: Event type name (``agent_start``, ``tool_call``, etc.).
        data:  Arbitrary payload dict.
    """

    event: str
    data: dict
